### ISSUE TITLE
MoreCosmetics Mod

### ISSUE THREAD

**Issue by Kolpixx** [MicrocontrollersDev/Alternatives#91]
Hey,

there is a nice mod for cosmetics they are all free and you can customise them. You can upload ur own capes (even animated capes) or search for capes from Youtubers like bedlessnoob and many others.

Here is a link: https://morecosmetics.org/

**Comment by MicrocontrollersDev** [comment]
It does look like a nice mod. I'll sit on this for a while. I'm not sure if I want to promote cosmetic mods including capes due to them breaking Minecraft EULA, but this does look better than those injectable cloak services. One I was looking at earlier was Cosmetica, and with it being open source I currently trust it more. This isn't something I plan on doing anytime soon though, but I'll look more into it when I do.

**Comment by Zetvue** [comment]
it ain't free bud
![image](https://user-images.githubusercontent.com/87939327/166167369-ab30edb4-dfb0-40b3-9007-202b6032e770.png)

**Comment by Zetvue** [comment]
also just grab essential cosmetics

**Comment by Zetvue** [comment]
also for some reason they have this???
![image](https://user-images.githubusercontent.com/87939327/166167515-ee42d8ec-65d5-4880-b7fb-5cf8d7c3cfba.png)
![image](https://user-images.githubusercontent.com/87939327/166167518-a9474d17-f250-4932-9a4a-caca514eac10.png)
yeah no, this ain't gettin in the catalog, sorry

**Comment by MicrocontrollersDev** [comment]
Oh damn I thought they were free. Yeah, then this is a no.
